# Generated by Django 5.1.3 on 2025-03-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_remove_team_coach_team_coaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
