# Generated by Django 5.1.3 on 2025-03-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_player_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coach_comments',
            field=models.TextField(blank=True),
        ),
    ]
