# Generated by Django 5.1.3 on 2025-03-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_division_league_draftpick_division_player_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpick',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='league.division'),
        ),
        migrations.AlterField(
            model_name='player',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.division'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league.division'),
        ),
    ]
