# Generated by Django 5.1.3 on 2025-03-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_alter_player_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='first', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='last', max_length=50),
            preserve_default=False,
        ),
    ]
