# Generated by Django 5.1.3 on 2025-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_division_coordinators_division_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bat_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='batting',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='catcher_pop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='conflict_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='exit_velo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fielding_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='five_ten_five_yards',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='grade_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='grip_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_league',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='last_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='last_team_coach',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='lateral_jump',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='other_activities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='parents_volunteering',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='past_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='personal_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pitching_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='primary_positions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_positions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='shot_put',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ten_yards',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='throwing',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='travel_before',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='travel_teams',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='travel_why',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='travel_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='volunteering_comments',
            field=models.TextField(blank=True),
        ),
    ]
