# Generated by Django 3.2.5 on 2025-03-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_alter_player_last_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='batting_throwing',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height_weight',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
