# Generated by Django 5.1.3 on 2025-03-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_team_city_team_country_team_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='players', to='league.team'),
        ),
    ]
