# Generated by Django 5.1.3 on 2025-03-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_game_playergamestat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
    ]
