# Generated by Django 5.1.3 on 2025-03-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_playerlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerlog',
            options={'ordering': ['-date'], 'verbose_name': 'Player Log', 'verbose_name_plural': 'Player Logs'},
        ),
        migrations.AlterField(
            model_name='playerlog',
            name='log_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('game', 'Game'), ('training', 'Training')], max_length=10),
        ),
    ]
