# Generated by Django 5.1.3 on 2025-03-24 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_alter_playerlog_options_alter_playerlog_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='league.player')),
            ],
        ),
    ]
