# Generated by Django 5.1.3 on 2025-03-24 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_playernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='league.player')),
            ],
        ),
    ]
