# Generated by Django 3.2.5 on 2025-03-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_playerjournalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('grip_strength', models.FloatField(blank=True, null=True)),
                ('lateral_jump', models.FloatField(blank=True, null=True)),
                ('shot_put', models.FloatField(blank=True, null=True)),
                ('five_ten_five_yards', models.FloatField(blank=True, null=True)),
                ('ten_yards', models.FloatField(blank=True, null=True)),
                ('catcher_pop', models.FloatField(blank=True, null=True)),
                ('fielding_notes', models.TextField(blank=True)),
                ('exit_velo', models.FloatField(blank=True, null=True)),
                ('bat_speed', models.FloatField(blank=True, null=True)),
                ('pitching_comment', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='league.player')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
