# Generated by Django 3.2.5 on 2025-03-25 02:45

from django.db import migrations

def migrate_player_evaluations(apps, schema_editor):
    Player = apps.get_model('league', 'Player')
    PerformanceEvaluation = apps.get_model('league', 'PerformanceEvaluation')

    for player in Player.objects.all():
        if (
            player.grip_strength is not None or
            player.lateral_jump is not None or
            player.shot_put is not None or
            player.five_ten_five_yards is not None or
            player.ten_yards is not None or
            player.catcher_pop is not None or
            player.exit_velo is not None or
            player.bat_speed is not None or
            player.fielding_notes or
            player.pitching_comment
        ):
            PerformanceEvaluation.objects.create(
                player=player,
                grip_strength=player.grip_strength,
                lateral_jump=player.lateral_jump,
                shot_put=player.shot_put,
                five_ten_five_yards=player.five_ten_five_yards,
                ten_yards=player.ten_yards,
                catcher_pop=player.catcher_pop,
                fielding_notes=player.fielding_notes,
                exit_velo=player.exit_velo,
                bat_speed=player.bat_speed,
                pitching_comment=player.pitching_comment,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0025_performanceevaluation'),
    ]

    operations = [
        migrations.RunPython(migrate_player_evaluations),
    ]
