# Generated by Django 3.2.5 on 2025-03-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_auto_20250325_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_away',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='league.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='league.team'),
        ),
    ]
