# Generated by Django 5.1.3 on 2025-03-31 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_auto_20250327_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.division'),
        ),
    ]
