# Generated by Django 5.1.3 on 2025-04-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_jointeamrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointeamrequest',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
