# Generated by Django 3.2.5 on 2025-04-02 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0030_alter_jointeamrequest_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signin_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
