# Generated by Django 3.2.5 on 2025-04-03 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0031_signinlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='source',
            field=models.CharField(choices=[('self', 'Self'), ('coach', 'Coach')], default='coach', max_length=20),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
