# Generated by Django 3.2.5 on 2025-05-16 21:40

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0033_fairplayruleset_lineupcompliance_lineupentry_lineupplan_playeravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='coordinators',
            field=models.ManyToManyField(related_name='coordinated_leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='league',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
