# Generated by Django 3.2.5 on 2025-05-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0034_auto_20250516_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='player',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
